export const links={github:'https://github.com/Wardieo/',linkedin:'https://www.linkedin.com/in/edward-vincent-mosquera-b25870245/',email:'mailto:edwardmosquera12345@gmail.com'}
export const projects=[
{number:'01',name:'Dayo Sports',kind:'Android app',description:'A player-focused mobile experience within the Dayo sports technology ecosystem.',tech:['React Native','Sports Technology'],href:'https://play.google.com/store/apps/details?id=com.dayosports.app&pcampaignid=web_share',platform:'google' as const,monogram:'DS'},
{number:'02',name:'Dayo Court',kind:'Android app',description:'A companion mobile product designed for the court side of the Dayo ecosystem.',tech:['React Native','Mobile Development'],href:'https://play.google.com/store/apps/details?id=com.dayoCourt&pcampaignid=web_share',platform:'google' as const,monogram:'DC'},
{number:'03',name:'Dayo Courts',kind:'Web platform',description:'A web experience for courts and the broader Dayo sports community.',tech:['Web Development','Sports Technology'],href:'https://dayo-courts.pages.dev/overview',platform:'web' as const,monogram:'DY'},
{number:'04',name:'Isora Photo Studio',kind:'Client website',description:'A clean, accessible web experience presenting photography services and visual content.',tech:['React.js','Web Development'],href:'https://isora-photostudio.vercel.app/',platform:'web' as const,monogram:'IS'},
{number:'05',name:'LinkCord',kind:'Web application / SSR',description:'A dashboard-oriented application developed as part of work-related software development activities.',tech:['React.js','SSR'],href:'https://linkcord-five.vercel.app/dashboard',platform:'web' as const,monogram:'LC'}]
export const experience=[
{initials:'DP',company:'DPWH District Engineering Office',type:'Internship',place:'Butuan City, Philippines',role:'Information & Communication Technology Intern',period:'FEB 2026 — MAR 2026',endDate:'2026-03',description:['Provided technical support for office printers, including setup, maintenance, and troubleshooting across different departments.','Assisted with basic hardware and software troubleshooting for office computers, network cable checking, and general IT maintenance.'],skills:['IT Support','Hardware','Software','Networking']},
{initials:'LS',company:'Leo Szac, MDS LLC · Upwork Inc.',type:'Contract',place:'Remote',role:'Automation Engineer',period:'JAN 2025 — APR 2025',endDate:'2025-04',description:['Developed and implemented Make.com automation workflows for a personalized book-generation system.','Built end-to-end processes that dynamically generated customized books while maintaining image consistency across outputs. Integrated tools and services to streamline content generation and support a scalable production workflow.'],skills:['Make.com','Automation','System Integration','Workflow Design']},
{initials:'SR',company:'Safer Road Rescue',type:'Operations',place:'USA-based company',role:'Agent & Dispatch',period:'APR 2026 — SEP 2026',endDate:'2026-09',description:['Provided roadside assistance support by handling customer calls, gathering service and location details, and coordinating with nearby service providers.','Dispatched vendors for towing and other roadside assistance requests while keeping communication clear between customers and providers.'],skills:['Customer Support','Dispatch','Coordination','Problem Solving']}]
export const stack=[['Development',['Python','JavaScript','React.js','React Native']],['Automation',['Make.com','Workflow Automation','System Integration','API Integration']],['IT & Systems',['IT Support','Technical Support','Hardware Troubleshooting','Software Troubleshooting','Networking']],['Development Tools',['Git','GitHub']],['Professional',['Technical Troubleshooting','Problem Solving','Customer Support','Technical Communication']]]
